analyzer:
  errors:
    depend_on_referenced_packages: ignore
    deprecated_member_use: ignore
    no_leading_underscores_for_local_identifiers: ignore
    unused_field: ignore
    use_build_context_synchronously: ignore
    use_super_parameters: ignore
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_single_quotes: true
    prefer_const_constructors: true
    prefer_const_constructors_in_immutables: true
    prefer_const_literals_to_create_immutables: true
    avoid_unnecessary_containers: true
    avoid_print: true
    always_specify_types: false
    unnecessary_this: true
    prefer_final_fields: true
    prefer_final_locals: true
    prefer_const_declarations: true
    avoid_redundant_argument_values: true
    sort_child_properties_last: true

    # ✅ الأداء وجودة الكود
    use_key_in_widget_constructors: true
    sized_box_for_whitespace: true
    prefer_relative_imports: true
    unnecessary_null_checks: true
    unnecessary_lambdas: true
    prefer_function_declarations_over_variables: true
    avoid_init_to_null: true
    avoid_returning_null_for_void: true
    avoid_shadowing_type_parameters: true
    avoid_type_to_string: true
    prefer_is_empty: true
    prefer_is_not_empty: true
    prefer_contains: true

    # ✅ الأمان والتنظيم
    unnecessary_null_in_if_null_operators: true
    prefer_asserts_in_initializer_lists: true
    prefer_typing_uninitialized_variables: true
    avoid_types_on_closure_parameters: true
    avoid_setters_without_getters: true
    parameter_assignments: true
    annotate_overrides: true
    constant_identifier_names: false # لأن بعض الثوابت تكون UPPER_CASE

    # ✅ تحسين التنسيق
    curly_braces_in_flow_control_structures: true
    require_trailing_commas: true
    sort_constructors_first: true
    sort_unnamed_constructors_first: true
    avoid_multiple_declarations_per_line: true
    file_names: true
    prefer_double_quotes: false
    lines_longer_than_80_chars: false

    # ✅ للتطبيقات الكبيرة
    public_member_api_docs: false
    directives_ordering: true
    unnecessary_await_in_return: true
    avoid_returning_null: true

