name: jump_time
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  flutter_riverpod: ^3.0.3
  
dev_dependencies:
  flutter_test:
    sdk: flutter

    
  flutter_lints: ^5.0.0
  image_picker: ^1.2.0
  
flutter:
  uses-material-design: true

  assets:
    - assets/images/